### ISSUE TITLE
Correctly format composer.json

### ISSUE THREAD

**Issue by Aleserche** [JincorTech/auth-php-client#4]
And remove composer.lock.

**Comment by hlogeon** [comment]
> And remove composer.lock.

You MUST keep composer.lock in repo. It is used to ensure that the versions installed in different environments(e.g. your local machine vs stage server) are the same! It is necessary because you are not forced to specify exact versions of packages but allowed to used expressions such as `*` and `^`.

**Comment by hlogeon** [comment]
never mind :)
